# build.yaml
# ...

targets:
  $default:
    builders:
      flutter_gen:
        options:
          output: lib/core/constants # Optional (default: lib/gen/)
          line_length: 120 # Optional (default: 80)
          # Optional
          integrations:
            flutter_svg: true
            rive: true
            lottie: true
      source_gen:combining_builder:
        generate_for:
          - "**/[!objectbox]**.dart"