name: uptodo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
# Database for the app
  drift: ^2.18.0

  flutter_dotenv: ^5.1.0
# state management
  flutter_bloc: ^8.1.5
# routing
  go_router: ^14.1.4
# dependency injection and functional Programming.
  get_it: ^7.7.0
  intl: ^0.19.0
  calendar_date_picker2: ^1.1.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner:
  flutter_gen_runner:
  intl_translation:
  intl_utils: ^2.8.7
  go_router_builder:

flutter_gen:
  output: lib/assets/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  outputs:
    # Specify the naming convention here
    naming: snake_case  # Options include snake_case, camelCase, etc.

flutter:
  uses-material-design: true
  generate: true # Enables generation of localized strings from arb files
  assets:
    - assets/icons/
    - assets/anim/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700