name: PR Merge Actions

on:
  push:
    branches:
      - dev

env:
  FLUTTER_VERSION: '3.27.1' # Set your desired Flutter version here
  DART_SDK_VERSION: '>=3.3.4 <4.0.0' # Dart SDK version from pubspec.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Run quality checks
        uses: ./.github/workflows/pr-quality-checks.yml
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to GitHub Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.sha }}
          tag: ${{ github.sha }}
          generate_release_notes: true
