name: PR Quality Checks

on:
  pull_request:
    branches:
      - dev

env:
  FLUTTER_VERSION: '3.0.0' # Set your desired Flutter version here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Clean Flutter project
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Reinstall dependencies
        run: flutter pub get

      - name: Lint code
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Check for merge conflicts
        run: git fetch origin dev && git checkout dev && git merge --no-commit --no-ff ${{ github.head_ref }}
